### ISSUE TITLE
Some questions about trajectory optimization

### ISSUE THREAD

**Issue by icameling** [hovren/kontiki#2]
Hello hovren

I add a new sensor model (LiDAR model) to the Kontiki, and I also create a new measurement type of the LiDAR model(`LiDARMeasurement`).

The R3 spline trajectory is initialized by solving a linear problem(Ax=b) and the SO3 spline trajectory is initialized by the optimation method. I have checked out the initial result and it's correct enough for the next step.

So I add  `AccelerometerMeasurement`, `GyroscopeMeasurement`, `LiDARMeasurement` to the estimator.  However, the optimization result is not right, especially in the front part of the trajectory, which is very unstable as shown in this picture.
![traj](https://user-images.githubusercontent.com/12575288/69851275-493b5c00-12bc-11ea-8fb0-bba7e79e68cb.png)

I have observed several things.

1. The optimization direction was wrong at the beginning. The terminal output during optimization is as follows. Note the first few iterations, the error is increasing
   ```
   iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
      0  3.082471e+10    0.00e+00    2.11e+09   0.00e+00   0.00e+00  1.00e+04        0    5.50e-02    6.00e-02
      1  5.499182e+11   -5.19e+11    0.00e+00   3.12e+01  -1.71e+01  5.00e+03        1    4.30e-02    1.03e-01
      2  6.604305e+11   -6.30e+11    0.00e+00   2.55e+01  -2.07e+01  1.25e+03        1    1.53e-02    1.18e-01
      3  6.878899e+10   -3.80e+10    0.00e+00   1.93e+01  -1.25e+00  1.56e+02        1    1.77e-02    1.36e-01
      4  1.021614e+10    2.06e+10    1.18e+09   1.30e+01   6.87e-01  1.65e+02        1    7.07e-02    2.07e-01
      5  3.401698e+09    6.81e+09    4.83e+08   6.37e+00   6.82e-01  1.73e+02        1    7.33e-02    2.80e-01
     ......
     28  8.597815e+08    6.39e+06    6.11e+07   6.52e-02   4.47e-01  9.30e-02        1    6.60e-02    1.52e+00
     29  8.494701e+08    1.03e+07    6.07e+07   9.56e-02   4.42e-01  9.29e-02        1    7.56e-02    1.60e+00
     30  8.439439e+08    5.53e+06    5.95e+07   6.33e-02   3.87e-01  9.18e-02        1    6.93e-02    1.67e+00
   
   Solver Summary (v 1.14.0-eigen-(3.3.7)-lapack-suitesparse-(4.4.6)-cxsparse-(3.1.4)-eigensparse-openmp-no_tbb)
   
                                        Original                  Reduced
   Parameter blocks                          372                      364
   Parameters                               1296                     1274
   Effective parameters                     1112                     1092
   Residual blocks                          9904                     9904
   Residuals                               24144                    24144
   
   Minimizer                        TRUST_REGION
   
   Sparse linear algebra library    SUITE_SPARSE
   Trust region strategy     LEVENBERG_MARQUARDT
   
                                           Given                     Used
   Linear solver          SPARSE_NORMAL_CHOLESKY   SPARSE_NORMAL_CHOLESKY
   Threads                                     8                        8
   Linear solver ordering              AUTOMATIC                      364
   
   Cost:
   Initial                          3.082471e+10
   Final                            8.439439e+08
   Change                           2.998077e+10
   
   Minimizer iterations                       31
   Successful steps                           21
   Unsuccessful steps                         10
   
   Time (in seconds):
   Preprocessor                         0.004960
   
     Residual only evaluation           0.139199 (30)
     Jacobian & residual evaluation     1.119277 (21)
     Linear solver                      0.345781 (30)
   Minimizer                            1.662274
   
   Postprocessor                        0.000659
   Total                                1.667893
   
   Termination:                   NO_CONVERGENCE (Maximum number of iterations reached. Number of iterations: 30.)
   ```

2. Given the adjacent control points in the quaternion spline, **the inner product of the first few konts is less than zero.**  
The inner product:
   ```
   control point idx: 0; q1^T q2 = -0.956805
   control point idx: 1; q1^T q2 = -0.999958
   control point idx: 3; q1^T q2 = -0.455493
   control point idx: 4; q1^T q2 = -0.84764
   ```
   The first few control points:
   ```
    control point q0 = -0.653931 -0.364804 -0.263813  0.608026
    control point q1 =  0.722436  0.239671  0.010041 -0.648493
    control point q2 = -0.720838  -0.24549 -0.016903  0.647952
    control point q3 = -0.729814  0.407561   0.49898  0.228658
    control point q4 =   -0.1708 -0.588182  -0.76801  0.187164
    control point q5 =  0.517802  0.181479  0.770429 -0.324632
    control point q6 =   0.575074  -0.721305 -0.0431002  -0.383603
   ```
I am wondering how to keep the inner product of the adjacent control points large than zero during the optimation. Could you give me some suggestions?  Thank you a lot !

**Comment by hovren** [comment]
Hi!

Happy to hear that you are working on LIDAR measurements, and I would be very interested to hear about your future results!

Regarding the issue, it's hard to debug without seeing your code.


The issue where the cost function value increases is not necessarily a problem since Ceres-solver can be run in a mode where the cost is allowed to increase, at least for a while.
It does however indicate that your starting solution is not great.

I didn't quite understand how you initialized the SO(3) spline, but it is important that the control point sequence that you start with has a consistent sign (i.e. `dot(q_i, q_(i+1)) > 0` for all `i`. It is sometimes sufficient to simply start with `q_i = (1, 0, 0, 0)`. If you start with some other control point sequence, just multiply offending control points by `-1` when necessary.
Obviously, the starting control point sequence must also be unitary, but this should already be enforced by kontiki when you add the control point.

That the control points switch sign during optimization is indeed troubling, but I am not sure there is much you can do here, apart from making sure that it starts in a consistent state. Most likely you have an issue with your measurements that makes this sign switch be the best solution.

Short list of things to check:

1. Does your Lidar and IMU measurements agree on the coordinate frame they are measuring in?
2. Are you sure that your LIDAR measurements are correctly implemented? Do you have a test suite with simulated data?
3. How are you weighting your measurements?
4. Did you select a knot spacing (spline `dt`) that is suitable? I have seen your first-iterations-are-bad issue when I have chosen a too dense (small `dt`).
5. Have you tried running without the IMU measurements?
6. What happens if you start the optimization at the ground truth (or very close to it)? Does it converge and stop, or does it diverge? Try with combinationatiosn of measurement classes to see when the error manifests itself.

**Comment by icameling** [comment]
Hi! 

Finally, I got the right result ~~~ Thank you very much for your detailed suggestions ~

In `LiDARMeasurement`, I modify the `AddToEstimator` function from
```
  void AddToEstimator(kontiki::TrajectoryEstimator<TrajectoryModel>& estimator) {
       ......
      std::vector<entity::ParameterInfo<double>> parameters;

       ......

      static std::vector<double*> params entity::ParameterInfo<double>::ToParameterBlocks(parameters);
      estimator.problem().AddResidualBlock(cost_function, nullptr,  params);
  }
```

to

```
  void AddToEstimator(kontiki::TrajectoryEstimator<TrajectoryModel>& estimator) {
       ......
      std::vector<entity::ParameterInfo<double>> parameters;

         ......

      estimator.problem().AddResidualBlock(cost_function, nullptr,
                                           entity::ParameterInfo<double>::ToParameterBlocks(parameters));
  }
```
It's my typo,  I add an extra `static` declaration on the variable `params`. I have forgotten where this wrong code copied from. It's `Ctrl`+`C` and `Ctrl`+`V` that has wasted so much of my time. :sob:

The result is as follows
![solved](https://user-images.githubusercontent.com/12575288/70208177-d15fac80-1767-11ea-98c6-07e2a127711a.png)


Thanks again for your excellent job.
